<?php
// includes/service-content.php — Textos extesos per servei (CA + ES + EN + FR + IT).
// Compartit entre pages/serveis.php (llistat d'un sol colp) i pages/servei.php
// (pàgina dedicada per servei), perquè el contingut no es duplique.
return [
    'disseny-web' => [
        'es' => '<p>En Alicante, tener una web lenta o anticuada es regalar clientes a la competencia. En AKRA diseñamos webs <strong>rápidas, modernas y optimizadas</strong> para el SEO desde el primer día. Cada web incluye: arquitectura SEO-first, Core Web Vitals optimizados, diseño responsive (mobile-first), integración con Google Analytics y Search Console, certificado SSL y protocolo HTTP/2.</p><p>Trabajamos con WordPress, desarrollo a medida y Shopify para ecommerce. Todas las webs pasan un test de velocidad (PageSpeed &gt;90) antes de la entrega.</p>',
        'ca' => '<p>A Alacant, tenir una web lenta o desfasada és regalar clients a la competència. A AKRA dissenyem webs <strong>ràpides, modernes i optimitzades</strong> per al SEO des del primer dia. Cada web inclou: arquitectura SEO-first, Core Web Vitals optimitzats, disseny responsive (mòbil primer), integració amb Google Analytics i Search Console, certificat SSL i protocol HTTP/2.</p><p>Treballem amb WordPress, desenvolupament a mida i Shopify per a comerç electrònic. Totes les webs passen un test de velocitat (PageSpeed &gt;90) abans del lliurament.</p>',
        'en' => '<p>In Alicante, a slow or outdated website is handing clients to your competitors. At AKRA we design <strong>fast, modern and SEO-optimised</strong> websites from day one. Every website includes: SEO-first architecture, optimised Core Web Vitals, responsive design (mobile-first), Google Analytics and Search Console integration, SSL certificate and HTTP/2.</p><p>We work with WordPress, custom development and Shopify for e-commerce. All websites pass a speed test (PageSpeed &gt;90) before delivery.</p>',
        'fr' => '<p>À Alicante, avoir un site lent ou dépassé, c\'est offrir des clients à la concurrence. Chez AKRA nous concevons des sites <strong>rapides, modernes et optimisés</strong> pour le SEO dès le premier jour. Chaque site inclut : architecture SEO-first, Core Web Vitals optimisés, design responsive (mobile-first), intégration Google Analytics et Search Console, certificat SSL et protocole HTTP/2.</p><p>Nous travaillons avec WordPress, développement sur mesure et Shopify pour l\'e-commerce. Tous les sites passent un test de vitesse (PageSpeed &gt;90) avant la livraison.</p>',
        'it' => '<p>Ad Alicante, avere un sito lento o obsoleto significa regalare clienti alla concorrenza. In AKRA progettiamo siti <strong>veloci, moderni e ottimizzati</strong> per il SEO dal primo giorno. Ogni sito include: architettura SEO-first, Core Web Vitals ottimizzati, design responsive (mobile-first), integrazione con Google Analytics e Search Console, certificato SSL e protocollo HTTP/2.</p><p>Lavoriamo con WordPress, sviluppo su misura e Shopify per l\'e-commerce. Tutti i siti superano un test di velocità (PageSpeed &gt;90) prima della consegna.</p>',
    ],
    'seo-local' => [
        'es' => '<p>El <strong>SEO local en Alicante</strong> es la estrategia más rentable para negocios que quieren clientes de la zona. Cuando alguien busca "dentista Alicante", "fontanero Benidorm" o "agencia web Costa Blanca", tiene que aparecer tu negocio. Nosotros lo conseguimos.</p><p>Nuestro servicio de SEO local incluye: optimización ficha Google My Business (GMB), estrategia de reseñas, keywords geolocalizadas, link building local, schema markup de negocio local e informes mensuales con posiciones reales.</p>',
        'ca' => '<p>El <strong>SEO local a Alacant</strong> és l\'estratègia més rendible per a negocis que volen clients de la zona. Quan algú cerca "dentista Alacant", "fontaner Benidorm" o "agència web Costa Blanca", ha d\'aparéixer el teu negoci. Nosaltres ho aconseguim.</p><p>El nostre servei de SEO local inclou: optimització fitxa Google My Business (GMB), estratègia de ressenyes, keywords geolocalizades, link building local, schema markup de negoci local i informes mensuals amb posicions reals.</p>',
        'en' => '<p><strong>Local SEO in Alicante</strong> is the most profitable strategy for businesses that want local clients. When someone searches "dentist Alicante", "plumber Benidorm" or "web agency Costa Blanca", your business needs to appear. We make it happen.</p><p>Our local SEO service includes: Google My Business (GMB) profile optimisation, review strategy, geolocated keywords, local link building, local business schema markup and monthly reports with real rankings.</p>',
        'fr' => '<p>Le <strong>SEO local à Alicante</strong> est la stratégie la plus rentable pour les entreprises qui veulent des clients locaux. Quand quelqu\'un cherche "dentiste Alicante", "plombier Benidorm" ou "agence web Costa Blanca", votre entreprise doit apparaître. Nous y arrivons.</p><p>Notre service de SEO local inclut : optimisation fiche Google My Business (GMB), stratégie d\'avis, mots-clés géolocalisés, link building local, schema markup entreprise locale et rapports mensuels avec positions réelles.</p>',
        'it' => '<p>Il <strong>SEO locale ad Alicante</strong> è la strategia più redditizia per le aziende che vogliono clienti locali. Quando qualcuno cerca "dentista Alicante", "idraulico Benidorm" o "agenzia web Costa Blanca", la tua azienda deve apparire. Noi lo realizziamo.</p><p>Il nostro servizio di SEO locale include: ottimizzazione scheda Google My Business (GMB), strategia di recensioni, keyword geolocalizzate, link building locale, schema markup attività locale e report mensili con posizioni reali.</p>',
    ],
    'marketing-digital' => [
        'es' => '<p>El marketing digital sin estrategia es gastar dinero sin saber adónde va. En AKRA diseñamos campañas orientadas a resultados medibles: <strong>Google Ads</strong>, Meta Ads (Instagram/Facebook), email marketing y estrategia de contenidos.</p><p>Trabajamos con un enfoque ROI: sabrás exactamente cuánto has gastado y cuánto has ganado. Auditoría inicial gratuita de tu cuenta de Google Ads si ya tienes una.</p>',
        'ca' => '<p>El màrqueting digital sense estratègia és gastar diners sense saber on van. A AKRA dissenyem campanyes orientades a resultats mesurables: <strong>Google Ads</strong>, Meta Ads (Instagram/Facebook), email marketing i estratègia de continguts.</p><p>Treballem amb un enfocament ROI: sabràs exactament quant has gastat i quant has guanyat. Auditoria inicial gratuïta del teu compte de Google Ads si ja en tens un.</p>',
        'en' => '<p>Digital marketing without strategy is spending money without knowing where it goes. At AKRA we design campaigns focused on measurable results: <strong>Google Ads</strong>, Meta Ads (Instagram/Facebook), email marketing and content strategy.</p><p>We work with an ROI focus: you\'ll know exactly how much you\'ve spent and how much you\'ve earned. Free initial audit of your Google Ads account if you already have one.</p>',
        'fr' => '<p>Le marketing digital sans stratégie, c\'est dépenser de l\'argent sans savoir où il va. Chez AKRA nous concevons des campagnes axées sur des résultats mesurables : <strong>Google Ads</strong>, Meta Ads (Instagram/Facebook), email marketing et stratégie de contenu.</p><p>Nous travaillons avec une approche ROI : vous saurez exactement combien vous avez dépensé et combien vous avez gagné. Audit initial gratuit de votre compte Google Ads si vous en avez déjà un.</p>',
        'it' => '<p>Il marketing digitale senza strategia è spendere denaro senza sapere dove va. In AKRA progettiamo campagne orientate a risultati misurabili: <strong>Google Ads</strong>, Meta Ads (Instagram/Facebook), email marketing e strategia dei contenuti.</p><p>Lavoriamo con un approccio ROI: saprai esattamente quanto hai speso e quanto hai guadagnato. Audit iniziale gratuito del tuo account Google Ads se ne hai già uno.</p>',
    ],
    'disseny-grafic' => [
        'es' => '<p>La identidad visual es la primera impresión que da tu empresa. En AKRA creamos <strong>logotipos y branding</strong> que reflejan tus valores y hacen que tu marca se recuerde.</p><p>Servicios: logotipo y variantes, manual de marca, carteles y banners, materiales corporativos (tarjetas, folletos, presentaciones), plantillas para redes sociales y packaging.</p>',
        'ca' => '<p>La identitat visual és la primera impressió que dona la teua empresa. A AKRA creem <strong>logotips i branding</strong> que reflecteixen els teus valors i fan que la teua marca es recorde.</p><p>Serveis: logotip i variants, manual de marca, cartells i banners, materials corporatius (targetes, fulletons, presentacions), plantilles per a xarxes socials i packaging.</p>',
        'en' => '<p>Visual identity is your company\'s first impression. At AKRA we create <strong>logos and branding</strong> that reflect your values and make your brand memorable.</p><p>Services: logo and variations, brand manual, posters and banners, corporate materials (business cards, brochures, presentations), social media templates and packaging.</p>',
        'fr' => '<p>L\'identité visuelle est la première impression que donne votre entreprise. Chez AKRA nous créons des <strong>logos et un branding</strong> qui reflètent vos valeurs et font que votre marque se souvient.</p><p>Services : logo et variantes, charte graphique, affiches et bannières, supports corporate (cartes, brochures, présentations), templates pour réseaux sociaux et packaging.</p>',
        'it' => '<p>L\'identità visiva è la prima impressione che dà la tua azienda. In AKRA creiamo <strong>loghi e branding</strong> che riflettono i tuoi valori e rendono il tuo marchio memorabile.</p><p>Servizi: logo e varianti, manuale del marchio, poster e banner, materiali corporate (biglietti, brochure, presentazioni), template per i social media e packaging.</p>',
    ],
    'xarxes-socials' => [
        'es' => '<p>La gestión de redes sociales profesional va mucho más allá de publicar fotos. En AKRA creamos contenido estratégico que <strong>conecta con tu audiencia</strong> y genera oportunidades de negocio reales.</p><p>Incluimos: estrategia editorial mensual, creación de contenido (copy + diseño), programación y publicación, respuesta a comentarios, analítica mensual y pruebas A/B.</p>',
        'ca' => '<p>La gestió de xarxes socials professional va molt més lluny de publicar fotos. A AKRA creem contingut estratègic que <strong>connecta amb la teua audiència</strong> i genera oportunitats de negoci reals.</p><p>Incloem: estratègia editorial mensual, creació de contingut (copy + disseny), programació i publicació, resposta a comentaris, analítica mensual i proves A/B.</p>',
        'en' => '<p>Professional social media management goes far beyond posting photos. At AKRA we create strategic content that <strong>connects with your audience</strong> and generates real business opportunities.</p><p>Includes: monthly editorial strategy, content creation (copy + design), scheduling and publishing, comment responses, monthly analytics and A/B testing.</p>',
        'fr' => '<p>La gestion professionnelle des réseaux sociaux va bien au-delà de publier des photos. Chez AKRA nous créons du contenu stratégique qui <strong>connecte avec votre audience</strong> et génère de vraies opportunités commerciales.</p><p>Inclus : stratégie éditoriale mensuelle, création de contenu (copy + design), programmation et publication, réponse aux commentaires, analytique mensuelle et tests A/B.</p>',
        'it' => '<p>La gestione professionale dei social media va ben oltre la pubblicazione di foto. In AKRA creiamo contenuti strategici che <strong>si connettono con il tuo pubblico</strong> e generano reali opportunità di business.</p><p>Include: strategia editoriale mensile, creazione di contenuti (copy + design), programmazione e pubblicazione, risposta ai commenti, analisi mensile e test A/B.</p>',
    ],
    'ecommerce' => [
        'es' => '<p>Una tienda online bien construida vende las 24h del día. En AKRA desarrollamos <strong>e-commerce</strong> que funcionan: con pasarelas de pago seguras, gestión de inventario, integración con sistemas de logística y SEO de producto.</p><p>Plataformas: WooCommerce (WordPress), Shopify, PrestaShop o solución a medida. Formación incluida para gestionar tu propio e-commerce.</p>',
        'ca' => '<p>Una botiga online ben construïda ven les 24h del dia. A AKRA desenvolupem <strong>e-commerce</strong> que funcionen: amb passarel·les de pagament segures, gestió d\'inventari, integració amb sistemes de logística i SEO de producte.</p><p>Plataformes: WooCommerce (WordPress), Shopify, PrestaShop o solució a mida. Formació inclosa per gestionar el teu propi e-commerce.</p>',
        'en' => '<p>A well-built online shop sells 24 hours a day. At AKRA we develop <strong>e-commerce</strong> that works: secure payment gateways, inventory management, logistics system integration and product SEO.</p><p>Platforms: WooCommerce (WordPress), Shopify, PrestaShop or custom solution. Training included to manage your own e-commerce.</p>',
        'fr' => '<p>Une boutique en ligne bien construite vend 24h/24. Chez AKRA nous développons des <strong>e-commerces</strong> qui fonctionnent : passerelles de paiement sécurisées, gestion des stocks, intégration avec les systèmes logistiques et SEO produit.</p><p>Plateformes : WooCommerce (WordPress), Shopify, PrestaShop ou solution sur mesure. Formation incluse pour gérer votre propre e-commerce.</p>',
        'it' => '<p>Un negozio online ben costruito vende 24 ore su 24. In AKRA sviluppiamo <strong>e-commerce</strong> che funzionano: gateway di pagamento sicuri, gestione dell\'inventario, integrazione con sistemi logistici e SEO di prodotto.</p><p>Piattaforme: WooCommerce (WordPress), Shopify, PrestaShop o soluzione su misura. Formazione inclusa per gestire il tuo e-commerce.</p>',
    ],
];